### ISSUE TITLE
website development

### ISSUE THREAD

**Issue by codePerfectPlus** [oke-aditya/about_me#1]
If you like I can help you in developing website either in `Django(Dynamic)` or `Jekyll(Static)`.

**Comment by oke-aditya** [comment]
I get the point what you are trying to say.
But I need is a portfolio page which does not need django. It will be hosted on GitHub pages so it cannot access any backend.

Jekyll pages are good but they are not for portfolios.

I just need a simple page / pages with HTML CSS (with bootrap) + JS. It should be responsive enough. 

I don't need advanced stuff such as React, Angular or SCSS etc.

The whole reason is I want a maintainable portfolio page which I will use for lot of years to come.

Jekyll is good but there is no development involved in there (I have used it) and it lacks ability to add content.

Let me know if this interests you !
